language: R
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

pandoc_version: 2.1.1

script:
  - Rscript -e 'bookdown::render_book("index.Rmd")'
  - cp _redirects _book/_redirects # netlify redirects file

before_cache:
- nvm install stable
- npm install netlify-cli -g

before_install:
  - export COMMIT_MSG=$(echo "$TRAVIS_COMMIT_MESSAGE" | head -n1)
  - export DEPLOY_MSG="${TRAVIS_COMMIT:0:7} ${COMMIT_MSG:0:50}"
env:
  - NETLIFY_SITE_ID=82ff5a18-8a13-4f25-b688-230b04bc5664
  # NETLIFY_AUTH_TOKEN set in travis settings


deploy:
  - provider: script
    #script: netlify deploy --dir _book --prod --message "$TRAVIS_COMMIT"
    script: netlify deploy --dir _book --prod --message "$DEPLOY_MSG"    
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    #script: netlify deploy --dir _book --message "$TRAVIS_BRANCH"
    script: netlify deploy --dir _book --message "$DEPLOY_MSG"    
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != "master"
